apiVersion: v1
kind: Secret
metadata:
  name: gitea-postgres-secret
  namespace: gitea
type: Opaque
data:
  POSTGRES_PASSWORD: "REPLACE_ME"
  POSTGRES_USER: "REPLACE_ME"
  POSTGRES_DB: "REPLACE_ME"
---
apiVersion: v1
kind: Secret
metadata:
  name: gitea-secret
  namespace: gitea
type: Opaque
data:
  SECRET_KEY: "REPLACE_ME"
  INTERNAL_TOKEN: "REPLACE_ME"
  DB_PASSWD: "REPLACE_ME"
  ADMIN_PASSWORD: "REPLACE_ME"
